# Generated by Django 3.1.7 on 2021-07-28 18:40

from django.db import migrations, models
import django.db.models.deletion
import gellert_apps.api.models.IoTClient
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='IoTClient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('client_type', models.CharField(choices=[('agristar2', 'Agristar2'), ('agristar2_unsecured', 'Unsecured Agristar2')], default='agristar2', max_length=50)),
                ('iot_hub_name', models.CharField(default='IoTHubGellert', max_length=50)),
                ('token', models.CharField(default=gellert_apps.api.models.IoTClient.get_default_token, max_length=25, unique=True)),
                ('token_spent', models.BooleanField(default=False)),
                ('unsecured_ip', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'IoT Client',
                'db_table': 'IoTClient',
            },
        ),
        migrations.CreateModel(
            name='IoTLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time_stamp', models.DateTimeField()),
                ('payload', models.JSONField()),
            ],
            options={
                'verbose_name': 'IoT Log',
                'db_table': 'IoTLog',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Organization',
                'db_table': 'Organization',
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'Site',
            },
        ),
        migrations.CreateModel(
            name='SiteEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('created_at_server', models.DateTimeField(auto_now_add=True)),
                ('updated_at_server', models.DateTimeField(auto_now=True)),
                ('dismissed', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Site Event',
                'db_table': 'SiteEvent',
            },
        ),
        migrations.CreateModel(
            name='SiteGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'SiteGroup',
            },
        ),
        migrations.CreateModel(
            name='CorporateAccount',
            fields=[
                ('organization_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.organization')),
            ],
            options={
                'verbose_name': 'Corporate Account',
                'db_table': 'CorporateAccount',
            },
            bases=('api.organization',),
        ),
        migrations.CreateModel(
            name='CustomerAccount',
            fields=[
                ('organization_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.organization')),
            ],
            options={
                'verbose_name': 'Customer Account',
                'db_table': 'CustomerAccount',
            },
            bases=('api.organization',),
        ),
        migrations.CreateModel(
            name='DealerAccount',
            fields=[
                ('organization_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.organization')),
            ],
            options={
                'verbose_name': 'Dealer Account',
                'db_table': 'DealerAccount',
            },
            bases=('api.organization',),
        ),
        migrations.CreateModel(
            name='SiteDealerEvent',
            fields=[
                ('siteevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.siteevent')),
            ],
            options={
                'verbose_name': 'Site Dealer Event',
                'db_table': 'SiteDealerEvent',
            },
            bases=('api.siteevent',),
        ),
        migrations.CreateModel(
            name='SiteZone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_api.sitezone_set+', to='contenttypes.contenttype')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='api.site')),
            ],
            options={
                'verbose_name': 'Site Zone',
                'db_table': 'SiteZone',
            },
        ),
    ]
