# Generated by Django 3.1.7 on 2021-07-28 18:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteevent',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='my_site_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='siteevent',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_api.siteevent_set+', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='siteevent',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_events', to='api.site'),
        ),
        migrations.AddField(
            model_name='siteevent',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recent_event_updates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='site',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_api.site_set+', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='site',
            name='site_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sites', to='api.sitegroup'),
        ),
        migrations.AddField(
            model_name='organization',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subsidiaries', to='api.organization'),
        ),
        migrations.AddField(
            model_name='organization',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_api.organization_set+', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='iotlog',
            name='iot_client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iot_client_logs', to='api.iotclient'),
        ),
        migrations.AddField(
            model_name='iotclient',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='iot_devices', to='api.site'),
        ),
        migrations.AddField(
            model_name='sitegroup',
            name='customer_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_groups', to='api.customeraccount'),
        ),
        migrations.AddField(
            model_name='sitedealerevent',
            name='dealer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dealer_events', to='api.dealeraccount'),
        ),
        migrations.AddField(
            model_name='site',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sites', to='api.customeraccount'),
        ),
    ]
