# Generated by Django 3.1.7 on 2021-07-29 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210728_1240'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='iotclient',
            options={'permissions': [('access_level1', 'Can access Agristar level 1.'), ('access_level2', 'Can access Agristar level 2.')], 'verbose_name': 'IoT Client'},
        ),
        migrations.AlterField(
            model_name='organization',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subsidiaries', to='api.organization'),
        ),
    ]
