# Generated by Django 3.1.7 on 2021-07-29 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210729_1034'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='iotclient',
            options={'permissions': [('access_level1_IoTClient', 'Can access Agristar level 1.'), ('access_level2_IoTClient', 'Can access Agristar level 2.')], 'verbose_name': 'IoT Client'},
        ),
    ]
