# Generated by Django 3.1.7 on 2021-09-16 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210729_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='iotclient',
            name='name',
            field=models.CharField(blank=True, default='Agri-Star', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='iotclient',
            name='client_type',
            field=models.CharField(choices=[('agristar1', 'Agristar1'), ('agristar2', 'Agristar2')], default='agristar2', max_length=50),
        ),
    ]
