# Generated by Django 3.1.7 on 2021-10-28 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210916_1619'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upgrade',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('version', models.CharField(max_length=25)),
                ('payload', models.FileField(upload_to='')),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Upgrade File',
                'db_table': 'Upgrade',
            },
        ),
        migrations.CreateModel(
            name='HttpMessageQueue',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('method', models.CharField(default='settings', max_length=25)),
                ('payload', models.JSONField()),
                ('is_processed', models.BooleanField(default=False)),
                ('iot_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.iotclient')),
            ],
            options={
                'verbose_name': 'Http Message Queue',
                'db_table': 'HttpMessageQueue',
            },
        ),
    ]
