# Generated by Django 3.1.7 on 2022-08-01 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_httpmessagequeue_upgrade'),
    ]

    operations = [
        migrations.AddField(
            model_name='httpmessagequeue',
            name='validation',
            field=models.JSONField(null=True),
        ),
    ]
