# Generated by Django 3.1.7 on 2022-08-15 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_httpmessagequeue_validation'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpgradeFile',
            fields=[
                ('id', models.TextField(max_length=100, primary_key=True, serialize=False)),
                ('content', models.BinaryField()),
                ('size', models.BigIntegerField()),
            ],
            options={
                'verbose_name': 'Upgrade File Content',
                'db_table': 'UpgradeFile',
            },
        ),
    ]
