# Generated by Django 3.1.7 on 2022-09-18 19:46

from django.db import migrations, models
import gellert_apps.api.database_storage
import gellert_apps.api.models.IoTClient


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_upgradefile'),
    ]

    operations = [
        migrations.AddField(
            model_name='iotclient',
            name='last_log',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='iotclient',
            name='time_stamp',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='httpmessagequeue',
            name='is_processed',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='iotclient',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='iotclient',
            name='token',
            field=models.CharField(db_index=True, default=gellert_apps.api.models.IoTClient.get_default_token, max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='upgrade',
            name='payload',
            field=models.FileField(storage=gellert_apps.api.database_storage.DatabaseStorage(), upload_to=''),
        ),
    ]
