# Generated by Django 3.1.7 on 2022-09-22 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20220918_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iotclient',
            name='last_log',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='iotclient',
            name='time_stamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
