# Generated by Django 3.1.7 on 2022-11-29 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20220922_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='iotclient',
            name='front_matter',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='iotclient',
            name='realtime',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='iotclient',
            name='settings',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
