# Generated by Django 4.2.5 on 2023-09-27 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_organization_polymorphic_ctype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersites',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
