# Generated by Django 4.2.5 on 2023-09-28 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_usersites_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iotclient',
            name='iot_hub_name',
            field=models.CharField(default='USWest', max_length=50),
        ),
    ]
