# Generated by Django 4.2.5 on 2024-09-16 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_iotclient_iot_hub_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='iotclient',
            name='time_zone',
            field=models.CharField(default='America/Boise', max_length=50),
        ),
    ]
