# Generated by Django 4.2.5 on 2025-06-09 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_iotclient_time_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='iotclient',
            name='location_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
