# Generated by Django 4.2.5 on 2026-04-14 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_add_location_id_to_iotclient'),
    ]

    operations = [
        migrations.AddField(
            model_name='httpmessagequeue',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
